import { co2, deviceEndpoints, humidity, numeric, temperature } from "zigbee-herdsman-converters/lib/modernExtend";

export default {
    zigbeeModel: ["SEN66+ESP32-C6"],
    fingerprint: [{ modelID: "SEN66+ESP32-C6", manufacturerName: "Custom" }],
    model: "SEN66+ESP32-C6",
    vendor: "Custom",
    description: "Air quality sensor",
    extend: [
        deviceEndpoints({ endpoints: { 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18 } }),
        numeric({
            access: "STATE_GET",
            endpointNames: ["12"],
            cluster: "genAnalogInput",
            attribute: "presentValue",
            label: "PM1",
            name: "PM1",
            unit: "µg/m³",
            precision: 1,
            reporting: { min: 60, max: 60 * 5, change: 0.1 },
        }),
        numeric({
            access: "STATE_GET",
            endpointNames: ["13"],
            cluster: "pm25Measurement",
            attribute: "measuredValue",
            label: "PM2_5",
            name: "PM2_5",
            unit: "µg/m³",
            precision: 1,
            reporting: { min: 60, max: 60 * 5, change: 0.1 },
        }),
        numeric({
            access: "STATE_GET",
            endpointNames: ["14"],
            cluster: "genAnalogInput",
            attribute: "presentValue",
            label: "PM4",
            name: "PM4",
            unit: "µg/m³",
            precision: 1,
            reporting: { min: 60, max: 60 * 5, change: 0.1 },
        }),
        numeric({
            access: "STATE_GET",
            endpointNames: ["15"],
            cluster: "genAnalogInput",
            attribute: "presentValue",
            label: "PM10",
            name: "PM10",
            unit: "µg/m³",
            precision: 1,
            reporting: { min: 60, max: 60 * 5, change: 0.1 },
        }),
        humidity({
            reporting: { min: 60, max: 60 * 5, change: 0.1 },
        }),
        temperature({
            reporting: { min: 60, max: 60 * 5, change: 0.1 },
        }),
        numeric({
            access: "STATE_GET",
            endpointNames: ["16"],
            cluster: "genAnalogInput",
            attribute: "presentValue",
            label: "VOC_Index",
            name: "VOC_Index",
            unit: "pts",
            reporting: { min: 60, max: 60 * 5, change: 1 },
        }),
        numeric({
            access: "STATE_GET",
            endpointNames: ["17"],
            cluster: "genAnalogInput",
            attribute: "presentValue",
            label: "NOx_Index",
            name: "NOx_Index",
            unit: "pts",
            reporting: { min: 60, max: 60 * 5, change: 1 },
        }),
        co2({
            endpointNames: ["18"],
            reporting: { min: 60, max: 60 * 5, change: 1 },
        }),
    ],
    meta: { multiEndpoint: true },
};